services:
  tor-nginx:
    container_name: "ft_onion"
    hostname: "ft_onion"
    build:
      context: .
      secrets:
        - pubkey
    ports:
      - "4242:4242"

secrets:
  pubkey:
    file: ${PUB_KEY_PATH}
