.PHONY: reverse infect

reverse:
	@echo "Reversing the infection!"
	@./stockholm.py -r "ThisIsAnExampleKey"

infect:
	@echo "Infecting files!"
	@export STOCKHOLM_KEY=ThisIsAnExampleKey && ./stockholm.py
